AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'db/**/*'

Layout/LineLength:
  Max: 155

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false
